apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: gke-dev-to-prod-app
build:
  artifacts:
  - image: gcr.io/agmsb-k8s/gke-flask-app
    buildpacks:
      builder: "gcr.io/buildpacks/builder:v1"
deploy:
  kustomize:
    paths:
    - https://github.com/agmsbush/gke-dev-to-prod-blueprints/
profiles:
- name: dev
  deploy:
    kustomize:
      paths:
      - ../config
- name: prod
  deploy:
    kustomize:
      paths:
      - https://github.com/agmsbush/gke-dev-to-prod-blueprints/overlays/prod